
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'CHEPE EQUALS LPAREN NUMBER PLUS RPAREN STRING TIMES VARIABLE\n    statement : CHEPE LPAREN expression RPAREN\n             | CHEPE LPAREN ChepeVar RPAREN\n    \n    expression : VARIABLE\n    \n    ChepeVar : VARIABLE EQUALS expression\n                        | VARIABLE\n    \n    expression : STRING\n    \n    expression : expression PLUS term\n    \n    expression : term\n    \n    term : term TIMES factor\n    \n    term : factor\n    \n    factor : NUMBER\n    \n    factor : LPAREN expression RPAREN\n    '
    
_lr_action_items = {'CHEPE':([0,],[2,]),'$end':([1,14,16,],[0,-1,-2,]),'LPAREN':([2,3,4,15,17,18,],[3,4,4,4,4,4,]),'VARIABLE':([3,4,17,],[7,13,13,]),'STRING':([3,4,17,],[8,8,8,]),'NUMBER':([3,4,15,17,18,],[11,11,11,11,11,]),'RPAREN':([5,6,7,8,9,10,11,12,13,19,20,21,22,],[14,16,-3,-6,-8,-10,-11,19,-3,-12,-7,-4,-9,]),'PLUS':([5,7,8,9,10,11,12,13,19,20,21,22,],[15,-3,-6,-8,-10,-11,15,-3,-12,-7,15,-9,]),'EQUALS':([7,],[17,]),'TIMES':([9,10,11,19,20,22,],[18,-10,-11,-12,18,-9,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'statement':([0,],[1,]),'expression':([3,4,17,],[5,12,21,]),'ChepeVar':([3,],[6,]),'term':([3,4,15,17,],[9,9,20,9,]),'factor':([3,4,15,17,18,],[10,10,10,10,22,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statement","S'",1,None,None,None),
  ('statement -> CHEPE LPAREN expression RPAREN','statement',4,'p_statement','Chepe.py',56),
  ('statement -> CHEPE LPAREN ChepeVar RPAREN','statement',4,'p_statement','Chepe.py',57),
  ('expression -> VARIABLE','expression',1,'p_expression_variable','Chepe.py',63),
  ('ChepeVar -> VARIABLE EQUALS expression','ChepeVar',3,'p_ChepeVar','Chepe.py',73),
  ('ChepeVar -> VARIABLE','ChepeVar',1,'p_ChepeVar','Chepe.py',74),
  ('expression -> STRING','expression',1,'p_expression_string','Chepe.py',84),
  ('expression -> expression PLUS term','expression',3,'p_expression_plus','Chepe.py',90),
  ('expression -> term','expression',1,'p_expression_term','Chepe.py',96),
  ('term -> term TIMES factor','term',3,'p_term_times','Chepe.py',102),
  ('term -> factor','term',1,'p_term_factor','Chepe.py',108),
  ('factor -> NUMBER','factor',1,'p_factor_number','Chepe.py',114),
  ('factor -> LPAREN expression RPAREN','factor',3,'p_factor_expression','Chepe.py',120),
]
